-- =============================================================================
-- 0012  Private storage bucket for scans & receipts  (§4.8)
-- -----------------------------------------------------------------------------
-- A single PRIVATE bucket. Object paths are always prefixed with the owner's
-- uid ("<uid>/<kind>/<uuid>.<ext>") and generated by the backend — the client
-- never chooses a path. The storage RLS below is defence-in-depth: even a
-- client using the anon key can only touch objects under its own uid prefix.
-- Downloads use short-lived signed URLs minted by the backend after an
-- ownership re-check; the bucket is never public.
-- =============================================================================

insert into storage.buckets (id, name, public)
values ('scans', 'scans', false)
on conflict (id) do nothing;

-- The first path segment must equal the caller's uid. storage.foldername()
-- returns the path split on '/'; [1] is the top folder.
create policy "scans_read_own"
  on storage.objects for select to authenticated
  using (bucket_id = 'scans' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "scans_insert_own"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'scans' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "scans_update_own"
  on storage.objects for update to authenticated
  using (bucket_id = 'scans' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'scans' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "scans_delete_own"
  on storage.objects for delete to authenticated
  using (bucket_id = 'scans' and (storage.foldername(name))[1] = auth.uid()::text);
